In [1]:
import numpy as np

引入numpy模組
ndarray(N-dimemsional array)
一維陣列為vector，二維陣列為matrix

In [2]:
a = np.array([1, 2, 3, 4, 5])
print(type(a))
print(a[0], a[1], a[2], a[3], a[4])

<class 'numpy.ndarray'>
1 2 3 4 5


透過傳入list到numpy.array()創建陣列

In [7]:
L = [1,2,3]

In [8]:
A = np.array(L)
A += 1
A

array([2, 3, 4])

In [9]:
for i in range(len(L)):
    L[i] += 1
L

[2, 3, 4]

同樣運算結果是[2, 3, 4]，但因為運算數量少，所以看不出來，但實際上用numpy在大量處理運算時，會明顯快很多。
array:adding elements to a numpy array creates a new array and destroys the old one.
list:Elements can be added to a list without creating a whole new list.

In [10]:
a = np.array([1, 2, 3, 4, 5])
a[0] = 5
#  "=" ：指派
print(a)

[5 2 3 4 5]


In [11]:
a[3] = 0
print(a)

[5 2 3 0 5]


In [15]:
b = np.array([[1, 2, 3],[4, 5, 6]])
print(b[0, 0], b[0, 1], b[0, 2])
print(b[1, 0], b[1, 1], b[1, 2])
# b[0, 1]：第0列第1行，先左再上

1 2 3
4 5 6


In [16]:
b[0, 0] = 6
b[1, 2] = 1
print(b)

[[6 2 3]
 [4 5 1]]


In [17]:
b

array([[6, 2, 3],
       [4, 5, 1]])

In [18]:
# 指定元素型態的陣列
c = np.array([1, 2, 3, 4, 5], int)
print(c)
d = np.array((1, 2, 3, 4, 5), dtype=float)
print(d)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [21]:
a1 = np.arange(5)
print(a1)
b1 = np.arange(1,6,2) # 頭,尾,方向或值
print(b1)

[0 1 2 3 4]
[1 3 5]


In [25]:
c1 = np.zeros(2)
print(c1)
c2 = np.zeros((2,2))
print(c2)

[0. 0.]
[[0. 0.]
 [0. 0.]]


In [27]:
e1 = np.ones(2)
print(e1)
e2 = np.ones((2,2))
print(e2)

[1. 1.]
[[1. 1.]
 [1. 1.]]


In [28]:
f1 = np.arange(16)
print(f1)
f2 = f1.reshape((4,4)) # 變成二維陣列
print(f2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


陣列屬性：
dtype:
size:
shape:
itemsize:
ndim:
nbytes:

In [29]:
g1 = np.array([1, 2, 3, 4, 5])
for ele in g1:
    print(ele, end=" ")

1 2 3 4 5 

In [32]:
g2 = np.array([[1, 2],[3, 4],[5, 6]])
for ele in g2:
    print(ele, end=" ")
print()
for ele in g2:
    for item in ele:
        print(item, end=" ")

[1 2] [3 4] [5 6] 
1 2 3 4 5 6 

In [33]:
g2 = np.array([[1, 2],[3, 4],[5, 6]])
for ele in g2:
    print(ele, end=" ")
# print()
for ele in g2:
    for item in ele:
        print(item, end=" ")

[1 2] [3 4] [5 6] 1 2 3 4 5 6 

# 向量運算

In [34]:
h1 = np.array([1, 2, 3])
print(h1)
s = 5
print(s)

[1 2 3]
5


In [35]:
h2 = h1 + s
print(h2)
h2 = h1 - s
print(h2)
h2 = h1 * s
print(h2)
h2 = h1 / s
print(h2)
# 向量與純量可以相加、減、乘、除

[6 7 8]
[-4 -3 -2]
[ 5 10 15]
[0.2 0.4 0.6]


In [44]:
s2 = np.array([4, 5, 6])
h21 = h1 + s2
print(h21)
h21 = h1 - s2
print(h21)
h21 = h1 * s2
print(h21)
h21 = h1 / s2
print(h21)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [36]:
h3 = np.array([3, 2])
-h3

array([-3, -2])

In [37]:
3*h3

array([9, 6])

In [38]:
h3

array([3, 2])

In [49]:
h1

array([4, 5, 6])

In [50]:
s2

array([4, 5, 6])

In [48]:
print(s2)
print(h1)
h4 = s2.dot(h1)
print(h4)
# 4*1+5*2+6*3=32 點積運算(Dot Product) 點積和，結果會是一個純量。

[4 5 6]
[1 2 3]
32


In [51]:
park = np.array([3, 4])
norm_park = np.linalg.norm(park)
norm_park
# 

5.0

In [53]:
store = np.array([9, 12])
store_park = store - park
print(store_park)
norm_store_park = np.linalg.norm(store_park)
norm_store_park

[6 8]


10.0

In [54]:
j2 = np.array([1,2,3,4,5,6,7,8,9])
print(j2)
b, c, d = j2[1:3], j2[:4], j2[3:]
print(b, c, d)

[1 2 3 4 5 6 7 8 9]
[2 3] [1 2 3 4] [4 5 6 7 8 9]


In [55]:
e, f, g = j2[2:9:3], j2[::4], j2[::-1]
print(e, f, g)

[3 6 9] [1 5 9] [9 8 7 6 5 4 3 2 1]


array[start:end]

array[start:end:step]